spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: c##ming
    password: 123456

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update   # 更新表结构